{% set version = "1.1.1" %}


package:
  name: nanolyse
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nanolyse/NanoLyse-{{ version }}.tar.gz
  sha256: d5740116b92864dabb9d308471abcdab5e96c8f876ed380f1f573358f9ca6218

build:
  noarch: python
  entry_points:
    - NanoLyse=nanolyse.NanoLyse:main
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv

requirements:
  host:
    - python >=3
    - setuptools
  run:
    - python >=3
    - biopython
    - mappy >=2.2

test:
  imports:
    - nanolyse

  commands:
    - NanoLyse --help

about:
  home: https://github.com/wdecoster/NanoLyse
  license: MIT License
  summary: 'Removing lambda DNA control reads from fastq dataset'
  license_family: MIT
