package:
  name: motifscan
  version: 1.2.0

source:
  url: https://files.pythonhosted.org/packages/5c/ab/19b9e8656bdc2ee002c2c35f01019bff192a9f9e2ff56da990f5a1bc06c2/motifscan-1.2.0.tar.gz
  sha256: 2f9d98b4a1f15338bd8d1ce4b78fee379a9864bf9274487f0d744f74e8adef17

build:
  skip: True  # [py2k]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas >=0.17.0
    - scipy
    - matplotlib-base

test:
  imports:
    - motifscan
    - motifscan.io
    - motifscan.lib
  commands:
    - motifscan --help > /dev/null

about:
  home: https://github.com/shao-lab/MotifScan
  license: BSD License
  license_family: BSD
  license_file: LICENSE
  summary: A motif discovery tool to search for candidate targets of given motifs.
