{% set name = "motifscan" %}
{% set version = "1.2.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2f9d98b4a1f15338bd8d1ce4b78fee379a9864bf9274487f0d744f74e8adef17

build:
  number: 0
  noarch: python
  entry_points:
    - motifscan=motifscan.cli.main:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy >=1.15
    - pysam >=0.15.0
    - requests
    - scipy
    - matplotlib-base >=3.0.0
    - tqdm

test:
  imports:
    - motifscan
    - motifscan.cli
    - motifscan.genome
    - motifscan.io
    - motifscan.motif
    - motifscan.region
  commands:
    - motifscan --help > /dev/null

about:
  home: https://github.com/shao-lab/MotifScan
  license: BSD License
  license_family: BSD
  license_file: LICENSE
  summary: A motif discovery tool to search for candidate targets of given motifs.
