{% set version = '1.0.0' %}

package:
  name: r-tigger
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tigger_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tigger/tigger_{{ version }}.tar.gz
  sha256: 3b6421fd78233351dd50b7d338d81931293e808c7a30c0d859f5b2baebc0ac8a

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base
    - r-alakazam >=0.3.0
    - r-dplyr >=0.8.1
    - r-ggplot2 >=3.1.1
    - r-shazam >=0.2.0
    - r-doparallel
    - r-foreach
    - r-gridextra
    - r-gtools
    - r-iterators
    - r-lazyeval
    - r-rlang
    - r-stringi
    - r-tidyr
  run:
    - r-base
    - r-alakazam >=0.3.0
    - r-dplyr >=0.8.1
    - r-ggplot2 >=3.1.1
    - r-shazam >=0.2.0
    - r-doparallel
    - r-foreach
    - r-gridextra
    - r-gtools
    - r-iterators
    - r-lazyeval
    - r-rlang
    - r-stringi
    - r-tidyr

test:
  commands:
    - $R -e "library('tigger')"

about:
  home: http://tigger.readthedocs.io
  license: CC BY-SA 4.0
  summary: 'Infers the V genotype of an individual from immunoglobulin (Ig) repertoire sequencing
    data (AIRR-Seq, Rep-Seq). Includes detection of  any novel alleles. This information
    is then used to correct existing V  allele calls from among the sample sequences.
    Citations: Gadala-Maria, et al (2015) <doi:10.1073/pnas.1417683112>.'
  license_family: CC
